### PR TITLE
Config improvements (and also mixin rewrites)

### PR DESCRIPTION
**Pull request by macbrayne**
- switched the config format to TOML
- refactored some of the mixins:
  - reduced impact of WitherSkullEntityMixin
  - reduced impact of CaveSpiderEntityMixin
  - WIP: try to reduce impact of more mixins (by using more localized mixins)
- renamed CommandVars to ModConfig
- added save specific settings
- removed global settings (except for servers)

### CODE REVIEW

**Comment by macbrayne** [comment]
I also fixed the build not working by switching to 1.17.1 and switching to yarn build 32.

**Comment by Pepe20129** [comment]
Thank you. As this is my first mod the code is fairly bad and I appreciate your contributions.

**Comment by Mincraftr** [comment]
The config seems to get reset (when a client connects after a server restart?).

**Comment by macbrayne** [comment]
Sorry, my commit title was wrong: it actually doesn't fix the file not being actually created. It was just a fix that, if more options are added, they config file always contains the new options.

**Comment by Pepe20129** [comment]
No problem. Also I don't think it's necessary for it to be created automatically, as it's created when needed.

**Comment by macbrayne** [comment]
If nothing else breaks I think this PR can be merged

**Pull request merged**
